#!/bin/sh

module purge          || exit 1
module load gcc-9.3.0 || exit 1

./clean       || exit 1
mkdir -pv bin || exit 1

CC="gcc -g -Wall -Werror -Wextra -Wconversion -Wstrict-aliasing=2 -Wimplicit-fallthrough=2 -pedantic -D_XOPEN_SOURCE=600 -O2 -march=native -std=c17 -lm"

set -x

$CC test_price_model.c price_model.c -o bin/test_price_model   || exit 1
$CC test_gap_model.c                 -o bin/test_gap_model     || exit 1
$CC test_overlap_model.c             -o bin/test_overlap_model || exit 1

bin/test_price_model   || exit 1
bin/test_gap_model     || exit 1
bin/test_overlap_model || exit 1

echo all tests passed

