#!/bin/sh

./clean       || exit 1
mkdir -pv bin || exit 1

CC="gcc -g -Wall -Werror -Wextra -Wconversion -Wstrict-aliasing=2 -Wimplicit-fallthrough=2 -pedantic -D_XOPEN_SOURCE=600 -O2 -march=native -std=c17"

set -x

$CC test_price_model.c price_model.c -o bin/test_price_model || exit 1

bin/test_price_model || exit 1

echo all tests passed
