#!/bin/sh

module purge          || exit 1
module load gcc-9.3.0 || exit 1

./clean       || exit 1
mkdir -pv bin || exit 1

CC="gcc -g -Wall -Werror -Wextra -Wconversion -Wstrict-aliasing=2 -Wimplicit-fallthrough=2 -pedantic -D_XOPEN_SOURCE=600 -O2 -march=native -std=c17"

set -x

$CC test_sort_stable.c -o bin/test_sort_stable || exit 1

bin/test_sort_stable || exit 1

echo all tests passed
