//c_oracle_header is auto generated by build_bpf.sh
//to reflect the current status of oracle.h
mod c_oracle_header;

//do not link with C during unit tests (which are built in native architecture, unlike libpyth.o) 
#[cfg(target_arch = "bpf")]
#[link(name = "cpyth")]
extern "C" {
    fn c_entrypoint(input: *mut u8) -> u64;
}

//do not add an entry point during unit tests (which can't be linked to the C entrypoint as explained above) 
#[cfg(target_arch = "bpf")]
#[no_mangle]
pub extern "C" fn entrypoint(input: *mut u8) -> u64 {
    let c_ret_val = unsafe{c_entrypoint(input)};
    if c_ret_val == c_oracle_header::SUCCESSFULLY_UPDATED_AGGREGATE{
        //0 is the SUCCESS value for solana
        return 0;
    } else {
        return c_ret_val;
    }
}