name: Check Formatting

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: solana-labs/solana:v1.14.7 # cargo check will attempt the BPF binary build
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly-2023-03-01
        components: rustfmt, clippy
    - name: Install Solana
      run: |
        set -eux
        sh -c "$(curl -sSfL https://release.solana.com/v1.16.13/install)"

    - uses: pre-commit/action@v2.0.3
